### ISSUE TITLE
Module not found error: No module named lark

### ISSUE THREAD

**Issue by G-force78** [beothorn/OneClickStableDifusionAutomatic1111Colab#1]
Firstly thanks for this collab its been working great most of the time. Not too sure whats happening now but I did add a !git pull 

drive.mount('/content/drive/')
update = True #@param {type:"boolean"}
if os.path.isdir('/content/drive/MyDrive/asd1111'):
  print('GDrive folder already asd1111 exists, will use it')
  %cd '/content/drive/MyDrive/asd1111/stable-diffusion-webui'
  !git pull

command to update the WebUI as the previous one didnt have all the samplers or extensions feature. Would that have caused this?

Traceback (most recent call last):
  File "launch.py", line 206, in <module>
    start_webui()
  File "launch.py", line 200, in start_webui
    import webui
  File "/content/drive/MyDrive/asd1111/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers, upscaler
  File "/content/drive/MyDrive/asd1111/stable-diffusion-webui/modules/sd_samplers.py", line 10, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/drive/MyDrive/asd1111/stable-diffusion-webui/modules/prompt_parser.py", line 4, in <module>
    import lark
ModuleNotFoundError: No module named 'lark'

**Comment by beothorn** [comment]
Hey, if you mark the update checkbox it should update so you can just leave it checked as it is the default.

ModuleNotFoundError: No module named 'lark'

means somehow the lark dependency was no installed.

This should have been handled by this line

`!COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" python launch.py`

Weird it didn't.

I tried running it again with update on and I am having many issues with local changes. I will probably change it a little bit to be more robust and then you can try again.

For your issue, you could try installing the requirements adding somewhere before auto1111webui executes this:

`pip install -r requirements.txt`

**Comment by G-force78** [comment]
> Hey, if you mark the update checkbox it should update so you can just leave it checked as it is the default.
> 
> ModuleNotFoundError: No module named 'lark'
> 
> means somehow the lark dependency was no installed.
> 
> This should have been handled by this line
> 
> `!COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" python launch.py`
> 
> Weird it didn't.
> 
> I tried running it again with update on and I am having many issues with local changes. I will probably change it a little bit to be more robust and then you can try again.
> 
> For your issue, you could try installing the requirements adding somewhere before auto1111webui executes this:
> 
> `pip install -r requirements.txt`

Ok will take a look cheers

**Comment by G-force78** [comment]
> Hey, if you mark the update checkbox it should update so you can just leave it checked as it is the default.
> 
> ModuleNotFoundError: No module named 'lark'
> 
> means somehow the lark dependency was no installed.
> 
> This should have been handled by this line
> 
> `!COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" python launch.py`
> 
> Weird it didn't.
> 
> I tried running it again with update on and I am having many issues with local changes. I will probably change it a little bit to be more robust and then you can try again.
> 
> For your issue, you could try installing the requirements adding somewhere before auto1111webui executes this:
> 
> `pip install -r requirements.txt`

Couldnt work out which line to put that in I kept creating error codes, so my workaround was to get the launch.py and req files from this  Commit hash: ac085628540d0ec6a988fad93f5b8f2154209571 as I know this one works, and run everything without update on, then had to comment out line 82 and 202 of launch.py no idea if that will have broken anything lol. WEbUI launched but now Im back to not having the new samplers lol

Yup I broke something cant create anything .. AttributeError: 'State' object has no attribute 'get_job_timestamp'

Is there a way to add a model path to googles virtual collab drive for extra models that I dont have space on gdrive for? Or do they all have to be linked to the same folder?

**Comment by beothorn** [comment]
You could clone the repository and then copy the models from gdrive. This would require some changes to this notebook (basically a different one as this is already very simple).
Something like this maybe? (haven't tested it)

```
!nvidia-smi
from google.colab import drive
import os
import random
import string

drive.mount('/content/drive/')
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui 
!cp '/content/drive/MyDrive/asd1111/stable-diffusion-webui/model.ckpt' './model.cpkt'
!cp '/content/drive/MyDrive/asd1111/stable-diffusion-webui/models/Stable-diffusion/*' './models/Stable-diffusion/'
%cd stable-diffusion-webui
my_pass = ''.join(random.choice(string.ascii_letters + string.digits) for i in range(32))
os.environ["AUTO_USER"] = my_pass
print('==========================================')
print(f'User is user, your password is: {my_pass}')
print('==========================================')
!COMMANDLINE_ARGS="--share --gradio-debug --gradio-auth user:$AUTO_USER" REQS_FILE="requirements.txt" python launch.py
```

**Comment by beothorn** [comment]
I had some issues with one of the repositories and added a line to just remove it so launch.py will checkout it again.
`  !rm -rf '/content/drive/MyDrive/asd1111/stable-diffusion-webui/repositories/k-diffusion'`
Maybe if you restore the line you commented out and try again it will work.

**Comment by G-force78** [comment]
Ok cheers
