### ISSUE TITLE
RuntimeError: Couldn't checkout commit 5b3af030dd83e0297272d861c19477735d0317ec for K-diffusion.

### ISSUE THREAD

**Issue by stf6** [beothorn/OneClickStableDifusionAutomatic1111Colab#5]
Hey! thanks for this colab. I've been using it for months now.
I have no clue what happened but I keep getting this error since I last updated it (about 3 days ago) :

Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: 5b3af030dd83e0297272d861c19477735d0317ec...
Traceback (most recent call last):
  File "launch.py", line 360, in <module>
    prepare_environment()
  File "launch.py", line 302, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "launch.py", line 156, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 5b3af030dd83e0297272d861c19477735d0317ec for K-diffusion.
Command: "git" -C "repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting

==========================================
User is user, your password is: CclZnz3xuxd0sNIghvHucmB7SmdkkGMd
==========================================
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
Commit hash: ea9bd9fc7409109adcd61b897abc2c8881161256
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: 5b3af030dd83e0297272d861c19477735d0317ec...
Traceback (most recent call last):
  File "launch.py", line 360, in <module>
    prepare_environment()
  File "launch.py", line 302, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "launch.py", line 156, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 5b3af030dd83e0297272d861c19477735d0317ec for K-diffusion.
Command: "git" -C "repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting

What do I do to solve it ? Have not made any changes to the code.

**Comment by beothorn** [comment]
Looks like git has some issues with the executable bit
https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha 

Issue should be fixed with my latest commit.

**Comment by stf6** [comment]
> 
It is fixed. Thanks. 
You missed a quote in update cell  %cd '/content/drive/MyDrive/asd1111/stable-diffusion-webui^here

**Comment by ThinhVu** [comment]
"git" -C "/content/drive/MyDrive/asd1111/stable-diffusion-webui/repositories/k-diffusion" checkout 5b3af0

The commit with the hash `5b3af0` does not exist in the k-diffusion repository.

**Comment by ThinhVu** [comment]
<img width="1043" alt="Screenshot 2023-05-13 at 3 08 43 PM" src="https://github.com/beothorn/OneClickStableDifusionAutomatic1111Colab/assets/8122962/09bbb0bf-eba0-499d-9f93-73fefcf7f3de">

**Comment by ThinhVu** [comment]
@beothorn bo
Removing the hardcoded commit should fix the error.
